// Code generated by protoc-gen-go. DO NOT EDIT.
// source: book.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetBookDescReq struct {
	BookName             string   `protobuf:"bytes,1,opt,name=BookName,proto3" json:"BookName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookDescReq) Reset()         { *m = GetBookDescReq{} }
func (m *GetBookDescReq) String() string { return proto.CompactTextString(m) }
func (*GetBookDescReq) ProtoMessage()    {}
func (*GetBookDescReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{0}
}

func (m *GetBookDescReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookDescReq.Unmarshal(m, b)
}
func (m *GetBookDescReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookDescReq.Marshal(b, m, deterministic)
}
func (m *GetBookDescReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookDescReq.Merge(m, src)
}
func (m *GetBookDescReq) XXX_Size() int {
	return xxx_messageInfo_GetBookDescReq.Size(m)
}
func (m *GetBookDescReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookDescReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookDescReq proto.InternalMessageInfo

func (m *GetBookDescReq) GetBookName() string {
	if m != nil {
		return m.BookName
	}
	return ""
}

type BookDesc struct {
	BookName             string   `protobuf:"bytes,1,opt,name=BookName,proto3" json:"BookName,omitempty"`
	BookState            string   `protobuf:"bytes,2,opt,name=BookState,proto3" json:"BookState,omitempty"`
	BookIntro            string   `protobuf:"bytes,3,opt,name=BookIntro,proto3" json:"BookIntro,omitempty"`
	BookNumber           string   `protobuf:"bytes,4,opt,name=BookNumber,proto3" json:"BookNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookDesc) Reset()         { *m = BookDesc{} }
func (m *BookDesc) String() string { return proto.CompactTextString(m) }
func (*BookDesc) ProtoMessage()    {}
func (*BookDesc) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{1}
}

func (m *BookDesc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookDesc.Unmarshal(m, b)
}
func (m *BookDesc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookDesc.Marshal(b, m, deterministic)
}
func (m *BookDesc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookDesc.Merge(m, src)
}
func (m *BookDesc) XXX_Size() int {
	return xxx_messageInfo_BookDesc.Size(m)
}
func (m *BookDesc) XXX_DiscardUnknown() {
	xxx_messageInfo_BookDesc.DiscardUnknown(m)
}

var xxx_messageInfo_BookDesc proto.InternalMessageInfo

func (m *BookDesc) GetBookName() string {
	if m != nil {
		return m.BookName
	}
	return ""
}

func (m *BookDesc) GetBookState() string {
	if m != nil {
		return m.BookState
	}
	return ""
}

func (m *BookDesc) GetBookIntro() string {
	if m != nil {
		return m.BookIntro
	}
	return ""
}

func (m *BookDesc) GetBookNumber() string {
	if m != nil {
		return m.BookNumber
	}
	return ""
}

type GetBookDescResp struct {
	BooksDesc            []*BookDesc `protobuf:"bytes,1,rep,name=BooksDesc,proto3" json:"BooksDesc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetBookDescResp) Reset()         { *m = GetBookDescResp{} }
func (m *GetBookDescResp) String() string { return proto.CompactTextString(m) }
func (*GetBookDescResp) ProtoMessage()    {}
func (*GetBookDescResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{2}
}

func (m *GetBookDescResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookDescResp.Unmarshal(m, b)
}
func (m *GetBookDescResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookDescResp.Marshal(b, m, deterministic)
}
func (m *GetBookDescResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookDescResp.Merge(m, src)
}
func (m *GetBookDescResp) XXX_Size() int {
	return xxx_messageInfo_GetBookDescResp.Size(m)
}
func (m *GetBookDescResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookDescResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookDescResp proto.InternalMessageInfo

func (m *GetBookDescResp) GetBooksDesc() []*BookDesc {
	if m != nil {
		return m.BooksDesc
	}
	return nil
}

type GetBookDataReq struct {
	BookHref             string   `protobuf:"bytes,1,opt,name=BookHref,proto3" json:"BookHref,omitempty"`
	BookNumber           string   `protobuf:"bytes,2,opt,name=BookNumber,proto3" json:"BookNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookDataReq) Reset()         { *m = GetBookDataReq{} }
func (m *GetBookDataReq) String() string { return proto.CompactTextString(m) }
func (*GetBookDataReq) ProtoMessage()    {}
func (*GetBookDataReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{3}
}

func (m *GetBookDataReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookDataReq.Unmarshal(m, b)
}
func (m *GetBookDataReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookDataReq.Marshal(b, m, deterministic)
}
func (m *GetBookDataReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookDataReq.Merge(m, src)
}
func (m *GetBookDataReq) XXX_Size() int {
	return xxx_messageInfo_GetBookDataReq.Size(m)
}
func (m *GetBookDataReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookDataReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookDataReq proto.InternalMessageInfo

func (m *GetBookDataReq) GetBookHref() string {
	if m != nil {
		return m.BookHref
	}
	return ""
}

func (m *GetBookDataReq) GetBookNumber() string {
	if m != nil {
		return m.BookNumber
	}
	return ""
}

type GetBookDataResp struct {
	BookData             string   `protobuf:"bytes,1,opt,name=BookData,proto3" json:"BookData,omitempty"`
	BookNumber           string   `protobuf:"bytes,2,opt,name=BookNumber,proto3" json:"BookNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookDataResp) Reset()         { *m = GetBookDataResp{} }
func (m *GetBookDataResp) String() string { return proto.CompactTextString(m) }
func (*GetBookDataResp) ProtoMessage()    {}
func (*GetBookDataResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{4}
}

func (m *GetBookDataResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookDataResp.Unmarshal(m, b)
}
func (m *GetBookDataResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookDataResp.Marshal(b, m, deterministic)
}
func (m *GetBookDataResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookDataResp.Merge(m, src)
}
func (m *GetBookDataResp) XXX_Size() int {
	return xxx_messageInfo_GetBookDataResp.Size(m)
}
func (m *GetBookDataResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookDataResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookDataResp proto.InternalMessageInfo

func (m *GetBookDataResp) GetBookData() string {
	if m != nil {
		return m.BookData
	}
	return ""
}

func (m *GetBookDataResp) GetBookNumber() string {
	if m != nil {
		return m.BookNumber
	}
	return ""
}

type GetBookListReq struct {
	BookNumber           string   `protobuf:"bytes,1,opt,name=BookNumber,proto3" json:"BookNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookListReq) Reset()         { *m = GetBookListReq{} }
func (m *GetBookListReq) String() string { return proto.CompactTextString(m) }
func (*GetBookListReq) ProtoMessage()    {}
func (*GetBookListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{5}
}

func (m *GetBookListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookListReq.Unmarshal(m, b)
}
func (m *GetBookListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookListReq.Marshal(b, m, deterministic)
}
func (m *GetBookListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookListReq.Merge(m, src)
}
func (m *GetBookListReq) XXX_Size() int {
	return xxx_messageInfo_GetBookListReq.Size(m)
}
func (m *GetBookListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookListReq proto.InternalMessageInfo

func (m *GetBookListReq) GetBookNumber() string {
	if m != nil {
		return m.BookNumber
	}
	return ""
}

type GetBookListResp struct {
	BookList             []*BookChapter `protobuf:"bytes,1,rep,name=BookList,proto3" json:"BookList,omitempty"`
	BookNumber           string         `protobuf:"bytes,2,opt,name=BookNumber,proto3" json:"BookNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetBookListResp) Reset()         { *m = GetBookListResp{} }
func (m *GetBookListResp) String() string { return proto.CompactTextString(m) }
func (*GetBookListResp) ProtoMessage()    {}
func (*GetBookListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{6}
}

func (m *GetBookListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookListResp.Unmarshal(m, b)
}
func (m *GetBookListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookListResp.Marshal(b, m, deterministic)
}
func (m *GetBookListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookListResp.Merge(m, src)
}
func (m *GetBookListResp) XXX_Size() int {
	return xxx_messageInfo_GetBookListResp.Size(m)
}
func (m *GetBookListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookListResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookListResp proto.InternalMessageInfo

func (m *GetBookListResp) GetBookList() []*BookChapter {
	if m != nil {
		return m.BookList
	}
	return nil
}

func (m *GetBookListResp) GetBookNumber() string {
	if m != nil {
		return m.BookNumber
	}
	return ""
}

type BookChapter struct {
	Href                 string   `protobuf:"bytes,1,opt,name=Href,proto3" json:"Href,omitempty"`
	Length               string   `protobuf:"bytes,2,opt,name=Length,proto3" json:"Length,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookChapter) Reset()         { *m = BookChapter{} }
func (m *BookChapter) String() string { return proto.CompactTextString(m) }
func (*BookChapter) ProtoMessage()    {}
func (*BookChapter) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{7}
}

func (m *BookChapter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookChapter.Unmarshal(m, b)
}
func (m *BookChapter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookChapter.Marshal(b, m, deterministic)
}
func (m *BookChapter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookChapter.Merge(m, src)
}
func (m *BookChapter) XXX_Size() int {
	return xxx_messageInfo_BookChapter.Size(m)
}
func (m *BookChapter) XXX_DiscardUnknown() {
	xxx_messageInfo_BookChapter.DiscardUnknown(m)
}

var xxx_messageInfo_BookChapter proto.InternalMessageInfo

func (m *BookChapter) GetHref() string {
	if m != nil {
		return m.Href
	}
	return ""
}

func (m *BookChapter) GetLength() string {
	if m != nil {
		return m.Length
	}
	return ""
}

func (m *BookChapter) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type DownloadBookReq struct {
	BookNumber           string   `protobuf:"bytes,1,opt,name=BookNumber,proto3" json:"BookNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadBookReq) Reset()         { *m = DownloadBookReq{} }
func (m *DownloadBookReq) String() string { return proto.CompactTextString(m) }
func (*DownloadBookReq) ProtoMessage()    {}
func (*DownloadBookReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{8}
}

func (m *DownloadBookReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadBookReq.Unmarshal(m, b)
}
func (m *DownloadBookReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadBookReq.Marshal(b, m, deterministic)
}
func (m *DownloadBookReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadBookReq.Merge(m, src)
}
func (m *DownloadBookReq) XXX_Size() int {
	return xxx_messageInfo_DownloadBookReq.Size(m)
}
func (m *DownloadBookReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadBookReq.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadBookReq proto.InternalMessageInfo

func (m *DownloadBookReq) GetBookNumber() string {
	if m != nil {
		return m.BookNumber
	}
	return ""
}

type DownloadBookResp struct {
	BookData             []byte   `protobuf:"bytes,1,opt,name=BookData,proto3" json:"BookData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadBookResp) Reset()         { *m = DownloadBookResp{} }
func (m *DownloadBookResp) String() string { return proto.CompactTextString(m) }
func (*DownloadBookResp) ProtoMessage()    {}
func (*DownloadBookResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{9}
}

func (m *DownloadBookResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadBookResp.Unmarshal(m, b)
}
func (m *DownloadBookResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadBookResp.Marshal(b, m, deterministic)
}
func (m *DownloadBookResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadBookResp.Merge(m, src)
}
func (m *DownloadBookResp) XXX_Size() int {
	return xxx_messageInfo_DownloadBookResp.Size(m)
}
func (m *DownloadBookResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadBookResp.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadBookResp proto.InternalMessageInfo

func (m *DownloadBookResp) GetBookData() []byte {
	if m != nil {
		return m.BookData
	}
	return nil
}

func init() {
	proto.RegisterType((*GetBookDescReq)(nil), "grpc.GetBookDescReq")
	proto.RegisterType((*BookDesc)(nil), "grpc.BookDesc")
	proto.RegisterType((*GetBookDescResp)(nil), "grpc.GetBookDescResp")
	proto.RegisterType((*GetBookDataReq)(nil), "grpc.GetBookDataReq")
	proto.RegisterType((*GetBookDataResp)(nil), "grpc.GetBookDataResp")
	proto.RegisterType((*GetBookListReq)(nil), "grpc.GetBookListReq")
	proto.RegisterType((*GetBookListResp)(nil), "grpc.GetBookListResp")
	proto.RegisterType((*BookChapter)(nil), "grpc.BookChapter")
	proto.RegisterType((*DownloadBookReq)(nil), "grpc.DownloadBookReq")
	proto.RegisterType((*DownloadBookResp)(nil), "grpc.DownloadBookResp")
}

func init() { proto.RegisterFile("book.proto", fileDescriptor_1e89d0eaa98dc5d8) }

var fileDescriptor_1e89d0eaa98dc5d8 = []byte{
	// 384 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4d, 0x4f, 0xc2, 0x40,
	0x10, 0xa5, 0x50, 0x89, 0x0c, 0x04, 0x74, 0x82, 0xa4, 0x21, 0xc6, 0x90, 0x9e, 0x38, 0x60, 0x83,
	0x78, 0x35, 0x31, 0x2a, 0x89, 0x9a, 0xa0, 0x26, 0xe8, 0x0f, 0xb0, 0xe0, 0x0a, 0x84, 0x8f, 0xad,
	0xed, 0x1a, 0xef, 0xfa, 0xc7, 0xcd, 0x6c, 0x97, 0xee, 0xb6, 0x10, 0xf1, 0xd6, 0x37, 0x33, 0xef,
	0xe5, 0xcd, 0xdb, 0x29, 0xc0, 0x88, 0xf3, 0xb9, 0x17, 0x84, 0x5c, 0x70, 0xb4, 0x27, 0x61, 0x30,
	0x76, 0x3b, 0x50, 0xbd, 0x65, 0xe2, 0x9a, 0xf3, 0x79, 0x9f, 0x45, 0xe3, 0x21, 0xfb, 0xc0, 0x26,
	0xec, 0x13, 0x7c, 0xf4, 0x97, 0xcc, 0xb1, 0x5a, 0x56, 0xbb, 0x34, 0x4c, 0xb0, 0xfb, 0x6d, 0xc5,
	0x4d, 0x9a, 0xfd, 0x6b, 0x10, 0x8f, 0xa1, 0x44, 0xdf, 0xcf, 0xc2, 0x17, 0xcc, 0xc9, 0xcb, 0xa6,
	0x2e, 0xac, 0xbb, 0xf7, 0x2b, 0x11, 0x72, 0xa7, 0xa0, 0xbb, 0xb2, 0x80, 0x27, 0x00, 0x52, 0xe7,
	0x73, 0x39, 0x62, 0xa1, 0x63, 0xcb, 0xb6, 0x51, 0x71, 0x2f, 0xa1, 0x96, 0xb2, 0x1c, 0x05, 0xd8,
	0x89, 0x05, 0x23, 0x2a, 0x38, 0x56, 0xab, 0xd0, 0x2e, 0xf7, 0xaa, 0x1e, 0xed, 0xe7, 0x25, 0x63,
	0x7a, 0xc0, 0x1d, 0xe8, 0x9d, 0x7d, 0xe1, 0x1b, 0x3b, 0xdf, 0x85, 0xec, 0xdd, 0x5c, 0x85, 0x70,
	0xc6, 0x4e, 0x7e, 0xc3, 0xce, 0x83, 0xb6, 0x23, 0xd5, 0xa2, 0x60, 0x2d, 0x47, 0xd8, 0x94, 0x23,
	0xbc, 0x53, 0xae, 0x9b, 0x98, 0x1b, 0xcc, 0x22, 0x41, 0xe6, 0xd2, 0x0c, 0x6b, 0x83, 0xf1, 0x9a,
	0x18, 0x88, 0x19, 0x51, 0x80, 0xa7, 0xb1, 0x01, 0xc2, 0x2a, 0x8e, 0x43, 0x1d, 0xc7, 0xcd, 0xd4,
	0x0f, 0x04, 0x0b, 0x87, 0xc9, 0xc8, 0x4e, 0x4f, 0x4f, 0x50, 0x36, 0x88, 0x88, 0x60, 0x1b, 0x49,
	0xc9, 0x6f, 0x6c, 0x40, 0x71, 0xc0, 0x56, 0x13, 0x31, 0x55, 0x74, 0x85, 0xb0, 0x0e, 0x7b, 0x2f,
	0x33, 0xb1, 0x60, 0xea, 0x99, 0x63, 0xe0, 0x9e, 0x41, 0xad, 0xcf, 0xbf, 0x56, 0x0b, 0xee, 0xbf,
	0x91, 0xf0, 0x7f, 0xb6, 0xf4, 0xe0, 0x20, 0x4d, 0xd9, 0x92, 0x73, 0x45, 0xe7, 0xdc, 0xfb, 0xc9,
	0x83, 0x4d, 0x00, 0x2f, 0xa0, 0x6c, 0x9c, 0x0b, 0xd6, 0xe3, 0x20, 0xd2, 0x47, 0xdf, 0x3c, 0xda,
	0x52, 0x8d, 0x02, 0x37, 0x67, 0xb2, 0xe9, 0xf5, 0x32, 0xec, 0xf8, 0x7c, 0xb2, 0x6c, 0x75, 0x06,
	0x29, 0xb6, 0xcc, 0x39, 0xcd, 0x56, 0xef, 0x9b, 0x61, 0xaf, 0xdf, 0xd0, 0xcd, 0xe1, 0x15, 0x54,
	0xcc, 0x95, 0x51, 0x0d, 0x66, 0x92, 0x6b, 0x36, 0xb6, 0x95, 0x49, 0xa0, 0x6b, 0x8d, 0x8a, 0xf2,
	0x5f, 0x3f, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x1e, 0x87, 0x35, 0x78, 0xf9, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BookClient is the client API for Book service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BookClient interface {
	GetBookDesc(ctx context.Context, in *GetBookDescReq, opts ...grpc.CallOption) (*GetBookDescResp, error)
	GetBookData(ctx context.Context, in *GetBookDataReq, opts ...grpc.CallOption) (*GetBookDataResp, error)
	GetBookList(ctx context.Context, in *GetBookListReq, opts ...grpc.CallOption) (*GetBookListResp, error)
	DownloadBook(ctx context.Context, in *DownloadBookReq, opts ...grpc.CallOption) (Book_DownloadBookClient, error)
}

type bookClient struct {
	cc *grpc.ClientConn
}

func NewBookClient(cc *grpc.ClientConn) BookClient {
	return &bookClient{cc}
}

func (c *bookClient) GetBookDesc(ctx context.Context, in *GetBookDescReq, opts ...grpc.CallOption) (*GetBookDescResp, error) {
	out := new(GetBookDescResp)
	err := c.cc.Invoke(ctx, "/grpc.Book/GetBookDesc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookClient) GetBookData(ctx context.Context, in *GetBookDataReq, opts ...grpc.CallOption) (*GetBookDataResp, error) {
	out := new(GetBookDataResp)
	err := c.cc.Invoke(ctx, "/grpc.Book/GetBookData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookClient) GetBookList(ctx context.Context, in *GetBookListReq, opts ...grpc.CallOption) (*GetBookListResp, error) {
	out := new(GetBookListResp)
	err := c.cc.Invoke(ctx, "/grpc.Book/GetBookList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookClient) DownloadBook(ctx context.Context, in *DownloadBookReq, opts ...grpc.CallOption) (Book_DownloadBookClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Book_serviceDesc.Streams[0], "/grpc.Book/DownloadBook", opts...)
	if err != nil {
		return nil, err
	}
	x := &bookDownloadBookClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Book_DownloadBookClient interface {
	Recv() (*DownloadBookResp, error)
	grpc.ClientStream
}

type bookDownloadBookClient struct {
	grpc.ClientStream
}

func (x *bookDownloadBookClient) Recv() (*DownloadBookResp, error) {
	m := new(DownloadBookResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BookServer is the server API for Book service.
type BookServer interface {
	GetBookDesc(context.Context, *GetBookDescReq) (*GetBookDescResp, error)
	GetBookData(context.Context, *GetBookDataReq) (*GetBookDataResp, error)
	GetBookList(context.Context, *GetBookListReq) (*GetBookListResp, error)
	DownloadBook(*DownloadBookReq, Book_DownloadBookServer) error
}

// UnimplementedBookServer can be embedded to have forward compatible implementations.
type UnimplementedBookServer struct {
}

func (*UnimplementedBookServer) GetBookDesc(ctx context.Context, req *GetBookDescReq) (*GetBookDescResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBookDesc not implemented")
}
func (*UnimplementedBookServer) GetBookData(ctx context.Context, req *GetBookDataReq) (*GetBookDataResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBookData not implemented")
}
func (*UnimplementedBookServer) GetBookList(ctx context.Context, req *GetBookListReq) (*GetBookListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBookList not implemented")
}
func (*UnimplementedBookServer) DownloadBook(req *DownloadBookReq, srv Book_DownloadBookServer) error {
	return status.Errorf(codes.Unimplemented, "method DownloadBook not implemented")
}

func RegisterBookServer(s *grpc.Server, srv BookServer) {
	s.RegisterService(&_Book_serviceDesc, srv)
}

func _Book_GetBookDesc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookDescReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServer).GetBookDesc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Book/GetBookDesc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServer).GetBookDesc(ctx, req.(*GetBookDescReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Book_GetBookData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServer).GetBookData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Book/GetBookData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServer).GetBookData(ctx, req.(*GetBookDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Book_GetBookList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServer).GetBookList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Book/GetBookList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServer).GetBookList(ctx, req.(*GetBookListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Book_DownloadBook_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadBookReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BookServer).DownloadBook(m, &bookDownloadBookServer{stream})
}

type Book_DownloadBookServer interface {
	Send(*DownloadBookResp) error
	grpc.ServerStream
}

type bookDownloadBookServer struct {
	grpc.ServerStream
}

func (x *bookDownloadBookServer) Send(m *DownloadBookResp) error {
	return x.ServerStream.SendMsg(m)
}

var _Book_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Book",
	HandlerType: (*BookServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBookDesc",
			Handler:    _Book_GetBookDesc_Handler,
		},
		{
			MethodName: "GetBookData",
			Handler:    _Book_GetBookData_Handler,
		},
		{
			MethodName: "GetBookList",
			Handler:    _Book_GetBookList_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DownloadBook",
			Handler:       _Book_DownloadBook_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "book.proto",
}
