// Code generated by protoc-gen-go. DO NOT EDIT.
// source: book.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetBookDescReq struct {
	BookName             string   `protobuf:"bytes,1,opt,name=BookName,proto3" json:"BookName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookDescReq) Reset()         { *m = GetBookDescReq{} }
func (m *GetBookDescReq) String() string { return proto.CompactTextString(m) }
func (*GetBookDescReq) ProtoMessage()    {}
func (*GetBookDescReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{0}
}

func (m *GetBookDescReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookDescReq.Unmarshal(m, b)
}
func (m *GetBookDescReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookDescReq.Marshal(b, m, deterministic)
}
func (m *GetBookDescReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookDescReq.Merge(m, src)
}
func (m *GetBookDescReq) XXX_Size() int {
	return xxx_messageInfo_GetBookDescReq.Size(m)
}
func (m *GetBookDescReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookDescReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookDescReq proto.InternalMessageInfo

func (m *GetBookDescReq) GetBookName() string {
	if m != nil {
		return m.BookName
	}
	return ""
}

type BookDesc struct {
	BookName             string   `protobuf:"bytes,1,opt,name=BookName,proto3" json:"BookName,omitempty"`
	BookState            string   `protobuf:"bytes,2,opt,name=BookState,proto3" json:"BookState,omitempty"`
	BookIntro            string   `protobuf:"bytes,3,opt,name=BookIntro,proto3" json:"BookIntro,omitempty"`
	BookNumber           string   `protobuf:"bytes,4,opt,name=BookNumber,proto3" json:"BookNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookDesc) Reset()         { *m = BookDesc{} }
func (m *BookDesc) String() string { return proto.CompactTextString(m) }
func (*BookDesc) ProtoMessage()    {}
func (*BookDesc) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{1}
}

func (m *BookDesc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookDesc.Unmarshal(m, b)
}
func (m *BookDesc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookDesc.Marshal(b, m, deterministic)
}
func (m *BookDesc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookDesc.Merge(m, src)
}
func (m *BookDesc) XXX_Size() int {
	return xxx_messageInfo_BookDesc.Size(m)
}
func (m *BookDesc) XXX_DiscardUnknown() {
	xxx_messageInfo_BookDesc.DiscardUnknown(m)
}

var xxx_messageInfo_BookDesc proto.InternalMessageInfo

func (m *BookDesc) GetBookName() string {
	if m != nil {
		return m.BookName
	}
	return ""
}

func (m *BookDesc) GetBookState() string {
	if m != nil {
		return m.BookState
	}
	return ""
}

func (m *BookDesc) GetBookIntro() string {
	if m != nil {
		return m.BookIntro
	}
	return ""
}

func (m *BookDesc) GetBookNumber() string {
	if m != nil {
		return m.BookNumber
	}
	return ""
}

type GetBookDescResp struct {
	BooksDesc            []*BookDesc `protobuf:"bytes,1,rep,name=BooksDesc,proto3" json:"BooksDesc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetBookDescResp) Reset()         { *m = GetBookDescResp{} }
func (m *GetBookDescResp) String() string { return proto.CompactTextString(m) }
func (*GetBookDescResp) ProtoMessage()    {}
func (*GetBookDescResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{2}
}

func (m *GetBookDescResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookDescResp.Unmarshal(m, b)
}
func (m *GetBookDescResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookDescResp.Marshal(b, m, deterministic)
}
func (m *GetBookDescResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookDescResp.Merge(m, src)
}
func (m *GetBookDescResp) XXX_Size() int {
	return xxx_messageInfo_GetBookDescResp.Size(m)
}
func (m *GetBookDescResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookDescResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookDescResp proto.InternalMessageInfo

func (m *GetBookDescResp) GetBooksDesc() []*BookDesc {
	if m != nil {
		return m.BooksDesc
	}
	return nil
}

func init() {
	proto.RegisterType((*GetBookDescReq)(nil), "grpc.GetBookDescReq")
	proto.RegisterType((*BookDesc)(nil), "grpc.BookDesc")
	proto.RegisterType((*GetBookDescResp)(nil), "grpc.GetBookDescResp")
}

func init() { proto.RegisterFile("book.proto", fileDescriptor_1e89d0eaa98dc5d8) }

var fileDescriptor_1e89d0eaa98dc5d8 = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0xca, 0xcf, 0xcf,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x49, 0x2f, 0x2a, 0x48, 0x56, 0xd2, 0xe1, 0xe2,
	0x73, 0x4f, 0x2d, 0x71, 0xca, 0xcf, 0xcf, 0x76, 0x49, 0x2d, 0x4e, 0x0e, 0x4a, 0x2d, 0x14, 0x92,
	0xe2, 0xe2, 0x00, 0x71, 0xfd, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xe0,
	0x7c, 0xa5, 0x26, 0x46, 0x88, 0x24, 0x48, 0x2d, 0x3e, 0x85, 0x42, 0x32, 0x5c, 0x9c, 0x20, 0x76,
	0x70, 0x49, 0x62, 0x49, 0xaa, 0x04, 0x13, 0x58, 0x12, 0x21, 0x00, 0x93, 0xf5, 0xcc, 0x2b, 0x29,
	0xca, 0x97, 0x60, 0x46, 0xc8, 0x82, 0x05, 0x84, 0xe4, 0xb8, 0xb8, 0xc0, 0xe6, 0x94, 0xe6, 0x26,
	0xa5, 0x16, 0x49, 0xb0, 0x80, 0xa5, 0x91, 0x44, 0x94, 0xec, 0xb9, 0xf8, 0x51, 0x9c, 0x5c, 0x5c,
	0x20, 0xa4, 0x03, 0x31, 0xb0, 0x18, 0x24, 0x20, 0xc1, 0xa8, 0xc0, 0xac, 0xc1, 0x6d, 0xc4, 0xa7,
	0x07, 0xf2, 0x9f, 0x1e, 0x5c, 0x19, 0x42, 0x81, 0x91, 0x0b, 0x17, 0x0b, 0x88, 0x23, 0x64, 0xc3,
	0xc5, 0x8d, 0x64, 0x90, 0x90, 0x08, 0x44, 0x07, 0x6a, 0x70, 0x48, 0x89, 0x62, 0x11, 0x2d, 0x2e,
	0x50, 0x62, 0x48, 0x62, 0x03, 0x07, 0xa3, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xd0, 0xa0, 0xc7,
	0x5c, 0x54, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BookClient is the client API for Book service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BookClient interface {
	GetBookDesc(ctx context.Context, in *GetBookDescReq, opts ...grpc.CallOption) (*GetBookDescResp, error)
}

type bookClient struct {
	cc *grpc.ClientConn
}

func NewBookClient(cc *grpc.ClientConn) BookClient {
	return &bookClient{cc}
}

func (c *bookClient) GetBookDesc(ctx context.Context, in *GetBookDescReq, opts ...grpc.CallOption) (*GetBookDescResp, error) {
	out := new(GetBookDescResp)
	err := c.cc.Invoke(ctx, "/grpc.Book/GetBookDesc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookServer is the server API for Book service.
type BookServer interface {
	GetBookDesc(context.Context, *GetBookDescReq) (*GetBookDescResp, error)
}

// UnimplementedBookServer can be embedded to have forward compatible implementations.
type UnimplementedBookServer struct {
}

func (*UnimplementedBookServer) GetBookDesc(ctx context.Context, req *GetBookDescReq) (*GetBookDescResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBookDesc not implemented")
}

func RegisterBookServer(s *grpc.Server, srv BookServer) {
	s.RegisterService(&_Book_serviceDesc, srv)
}

func _Book_GetBookDesc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookDescReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServer).GetBookDesc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Book/GetBookDesc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServer).GetBookDesc(ctx, req.(*GetBookDescReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Book_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Book",
	HandlerType: (*BookServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBookDesc",
			Handler:    _Book_GetBookDesc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "book.proto",
}
